=== RichiHnok/JAVA_LAB2/src/main/resources/gems_schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="Gems">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Gem" type="GemType" minOccurs="16" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>		
	</xs:element>

	<xs:complexType name="GemType">
		<xs:sequence>
			<xs:element name= "Preciousness" type="PreciousnessType"/>
			<xs:element name="VisualParametres" type="VisualParametresType"/>
			<xs:element name="Value" type="xs:double"/>
		</xs:sequence>
		<xs:attribute name="gemId" type="xs:ID" use="required"/>
		<xs:attribute name="name" type="xs:string" use="required"/>
		<xs:attribute name="origin" type="xs:string" use="optional" default="Unknown"/>
	</xs:complexType>

	<xs:simpleType name="PreciousnessType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="Драгоценный"/>
			<xs:enumeration value="Полудрагоценный"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:complexType name="VisualParametresType">
		<xs:sequence>
			<xs:element name="Color" type="xs:string"/>
			<xs:element name="Transparency" type="xs:int"/>
			<xs:element name="Cut" type="CutType"/>
		</xs:sequence>
	</xs:complexType>

	<xs:simpleType name="CutType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="Овальная"/>
			<xs:enumeration value="Ступенчатая"/>
			<xs:enumeration value="Круглая"/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== RichiHnok/JAVA_LAB2/src/main/resources/gems.xml
<?xml version="1.0" encoding="UTF-8"?>
<Gems xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="gems_schema.xsd">
	<Gem gemId="a01" name="Рубин" origin="Мьянма">
		<Preciousness>Драгоценный</Preciousness>
		<VisualParametres>
			<Color>Ярко-красный</Color>
			<Transparency>90</Transparency>
			<Cut>Круглая</Cut>
		</VisualParametres>
		<Value>2.5</Value>
	</Gem>
	<Gem gemId="a02" name="Сапфир" origin="Шри-Ланка">
		<Preciousness>Драгоценный</Preciousness>
		<VisualParametres>
			<Color>Насыщенный синий</Color>
			<Transparency>85</Transparency>
			<Cut>Овальная</Cut>
		</VisualParametres>
		<Value>4</Value>
	</Gem>
	<Gem gemId="a03" name="Изумруд" origin="Колумбия">
		<Preciousness>Драгоценный</Preciousness>
		<VisualParametres>
			<Color>Глубокий зеленый</Color>
			<Transparency>80</Transparency>
			<Cut>Ступенчатая</Cut>
		</VisualParametres>
		<Value>1.8</Value>
	</Gem>
	<Gem gemId="a04" name="Аметист" origin="Бразилия">
		<Preciousness>Полудрагоценный</Preciousness>
		<VisualParametres>
			<Color>Насыщенный фиолетовый</Color>
			<Transparency>92</Transparency>
			<Cut>Овальная</Cut>
		</VisualParametres>
		<Value>6</Value>
	</Gem>
	<Gem gemId="a05" name="Гранат" origin="Танзания">
		<Preciousness>Полудрагоценный</Preciousness>
		<VisualParametres>
			<Color>Темно-красный</Color>
			<Transparency>88</Transparency>
			<Cut>Круглая</Cut>
		</VisualParametres>
		<Value>1.5</Value>
	</Gem>
	<Gem gemId="a06" name="Топаз" origin="Бразилия">
		<Preciousness>Полудрагоценный</Preciousness>
		<VisualParametres>
			<Color>Золотистый</Color>
			<Transparency>90</Transparency>
			<Cut>Овальная</Cut>
		</VisualParametres>
		<Value>8</Value>
	</Gem>
	<Gem gemId="a07" name="Аквамарин" origin="Бразилия">
		<Preciousness>Полудрагоценный</Preciousness>
		<VisualParametres>
			<Color>Бледно-голубой</Color>
			<Transparency>85</Transparency>
			<Cut>Ступенчатая</Cut>
		</VisualParametres>
		<Value>12</Value>
	</Gem>
	<Gem gemId="a08" name="Цитрин" origin="Бразилия">
		<Preciousness>Полудрагоценный</Preciousness>
		<VisualParametres>
			<Color>Лимонно-желтый</Color>
			<Transparency>92</Transparency>
			<Cut>Круглая</Cut>
		</VisualParametres>
		<Value>5</Value>
	</Gem>
	<Gem gemId="a09" name="Опал" origin="Австралия">
		<Preciousness>Полудрагоценный</Preciousness>
		<VisualParametres>
			<Color>Радужный</Color>
			<Transparency>88</Transparency>
			<Cut>Овальная</Cut>
		</VisualParametres>
		<Value>2.2</Value>
	</Gem>
	<Gem gemId="a10" name="Хризолит" origin="Пакистан">
		<Preciousness>Полудрагоценный</Preciousness>
		<VisualParametres>
			<Color>Глубокий зеленый</Color>
			<Transparency>85</Transparency>
			<Cut>Ступенчатая</Cut>
		</VisualParametres>
		<Value>6</Value>
	</Gem>
	<Gem gemId="a11" name="Турмалин" origin="Бразилия">
		<Preciousness>Полудрагоценный</Preciousness>
		<VisualParametres>
			<Color>Разноцветный (зеленый, розовый)</Color>
			<Transparency>90</Transparency>
			<Cut>Овальная</Cut>
		</VisualParametres>
		<Value>3</Value>
	</Gem>
	<Gem gemId="a12" name="Александрит" origin="Россия">
		<Preciousness>Драгоценный</Preciousness>
		<VisualParametres>
			<Color>Зелено-красный</Color>
			<Transparency>87</Transparency>
			<Cut>Овальная</Cut>
		</VisualParametres>
		<Value>1.2</Value>
	</Gem>
	<Gem gemId="a13" name="Циркон" origin="Таиланд">
		<Preciousness>Полудрагоценный</Preciousness>
		<VisualParametres>
			<Color>Бесцветный</Color>
			<Transparency>92</Transparency>
			<Cut>Круглая</Cut>
		</VisualParametres>
		<Value>3</Value>
	</Gem>
	<Gem gemId="a14" name="Кунцит" origin="Афганистан">
		<Preciousness>Полудрагоценный</Preciousness>
		<VisualParametres>
			<Color>Нежно-розовый</Color>
			<Transparency>88</Transparency>
			<Cut>Овальная</Cut>
		</VisualParametres>
		<Value>7</Value>
	</Gem>
	<Gem gemId="a15" name="Танзанит" origin="Танзания">
		<Preciousness>Драгоценный</Preciousness>
		<VisualParametres>
			<Color>Фиолетово-синий</Color>
			<Transparency>90</Transparency>
			<Cut>Ступенчатая</Cut>
		</VisualParametres>
		<Value>3.5</Value>
	</Gem>
	<Gem gemId="a16" name="Жадеит" origin="Мьянма">
		<Preciousness>Полудрагоценный</Preciousness>
		<VisualParametres>
			<Color>Ярко-зеленый</Color>
			<Transparency>85</Transparency>
			<Cut>Круглая</Cut>
		</VisualParametres>
		<Value>8</Value>
	</Gem>
</Gems>
